version: '3.8'

services:
  config-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config-client
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    external: true
