version: '3.8'

services:

  config_cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: config-client:1.0.0
    container_name: config-client
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
      - CONFIG_CLIENT_PORT=${CONFIG_CLIENT_PORT}
      - INTERNAL_PORT=${CONFIG_CLIENT_PORT}
    ports:
      - "${CONFIG_CLIENT_PORT}:${CONFIG_CLIENT_PORT}"
    networks:
      - my-network

networks:
  my-network:
    external: true
